# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - arm_02_link_joint
      - arm_04_link_joint
      - arm_06_link_joint
      - arm_08_link_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - arm_10_link_joint
      - arm_11_link_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true